import type { Metadata } from "next";
import { instrumentSerif, inter, jetbrainsMono } from "@/lib/fonts";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "nextjs-feature-based-boilerplate",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${instrumentSerif.variable} ${jetbrainsMono.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
